services:
  # --- Kafka (modo KRaft) ---
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    networks:
      - processing_net

  # --- Spark Master ---
  spark-master:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080"
      - "7077:7077"
    networks:
      - processing_net

  # --- Spark Worker ---
  spark-worker:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - processing_net

  # --- Nuestro Servicio de Procesamiento en Python ---
  python-processor:
    build:
      context: .
      dockerfile: ./dockers/python_processor/Dockerfile
    depends_on:
      - spark-master
      - spark-worker
    volumes:
          #  - ./data:/app/data --- Modificar esta linea permite realizar pruebas con los vídeos de la carpeta data
          # - ./data/processed:/app/data/processed -- Modificar esta linea permite realizar pruebas con los videos procesados
      - ./process:/app/process # Mapear la carpeta de procesamiento
      - /home/alvaro/.jitsi-meet-cfg/jibri/recordings/:/app/data # Mapear la carpeta de grabaciones de Jibri
    networks:
      - processing_net

networks:
  processing_net:
    driver: bridge